In [ ]:
from itertools import product
from operator import mul
from functools import reduce
import pandas as pd
from nltk.tokenize import RegexpTokenizer
import re

In [10]:
text="he bad news is that Trump did not articulate a new strategy for dealing with North Korea. He articulated \
a willingness to talk to North Korea, which is good, but he continued his insistence on denuclearization as a \
precondition for talks -- We are only prepared to discuss this brighter path for North Korea if its leaders cease \
their threats and dismantle their nuclear program -- which is not so much bad as it is pointless. North Korea will\
never denuclearize, and insisting on denuclearization as a precondition to talks is "

In [11]:
def my_tokenizer(text):
    tokenizer = RegexpTokenizer(r'\w+')
    tokens=[]
    for i in range(len(text)):
        helper=re.sub(r'(^https?:\/\/.*[\r\n]*)|(@[A-Za-z0-9]+)|([0-9])|(\w+:\/\/\S+)', '', 
                          text[i].lower(), flags=re.MULTILINE)
        tokens.append(tokenizer.tokenize(helper))
    return tokens

In [13]:
text_tokenized=my_tokenizer([text])

In [6]:
#example of counting letters in phrases

In [2]:
L1 = ['b', 'c', 'd', 'e', 't', 'w', 'x', 'y', 'z']
L2 = ['the onion', 'be your self', 'great zoo', 'x men', 'corn day']

phrase_map = {}

for phrase in L2:
    word_count = {word: phrase.count(word) for word in L1 if word in phrase}

    occurrence_map = {}
    for perm in product(word_count, repeat=2):
        occurrence_map[perm] = reduce(mul, (word_count[key] for key in perm), 1)

    phrase_map[phrase] = occurrence_map

In [3]:
phrase_map

{'be your self': {('b', 'b'): 1,
  ('b', 'e'): 2,
  ('b', 'y'): 1,
  ('e', 'b'): 2,
  ('e', 'e'): 4,
  ('e', 'y'): 2,
  ('y', 'b'): 1,
  ('y', 'e'): 2,
  ('y', 'y'): 1},
 'corn day': {('c', 'c'): 1,
  ('c', 'd'): 1,
  ('c', 'y'): 1,
  ('d', 'c'): 1,
  ('d', 'd'): 1,
  ('d', 'y'): 1,
  ('y', 'c'): 1,
  ('y', 'd'): 1,
  ('y', 'y'): 1},
 'great zoo': {('e', 'e'): 1,
  ('e', 't'): 1,
  ('e', 'z'): 1,
  ('t', 'e'): 1,
  ('t', 't'): 1,
  ('t', 'z'): 1,
  ('z', 'e'): 1,
  ('z', 't'): 1,
  ('z', 'z'): 1},
 'the onion': {('e', 'e'): 1, ('e', 't'): 1, ('t', 'e'): 1, ('t', 't'): 1},
 'x men': {('e', 'e'): 1, ('e', 'x'): 1, ('x', 'e'): 1, ('x', 'x'): 1}}

In [5]:
pd.DataFrame(phrase_map)

     be your self  corn day  great zoo  the onion  x men
b b           1.0       NaN        NaN        NaN    NaN
  e           2.0       NaN        NaN        NaN    NaN
  y           1.0       NaN        NaN        NaN    NaN
c c           NaN       1.0        NaN        NaN    NaN
  d           NaN       1.0        NaN        NaN    NaN
  y           NaN       1.0        NaN        NaN    NaN
d c           NaN       1.0        NaN        NaN    NaN
  d           NaN       1.0        NaN        NaN    NaN
  y           NaN       1.0        NaN        NaN    NaN
e b           2.0       NaN        NaN        NaN    NaN
  e           4.0       NaN        1.0        1.0    1.0
  t           NaN       NaN        1.0        1.0    NaN
  x           NaN       NaN        NaN        NaN    1.0
  y           2.0       NaN        NaN        NaN    NaN
  z           NaN       NaN        1.0        NaN    NaN
t e           NaN       NaN        1.0        1.0    NaN
  t           NaN       NaN        1.0        1.0    NaN
  z           NaN       NaN        1.0        NaN    NaN
x e           NaN       NaN        NaN        NaN    1.0
  x           NaN       NaN        NaN        NaN    1.0
y b           1.0       NaN        NaN        NaN    NaN
  c           NaN       1.0        NaN        NaN    NaN
  d           NaN       1.0        NaN        NaN    NaN
  e           2.0       NaN        NaN        NaN    NaN
  y           1.0       1.0        NaN        NaN    NaN
z e           NaN       NaN        1.0        NaN    NaN
  t           NaN       NaN        1.0        NaN    NaN
  z           NaN       NaN        1.0        NaN    NaN